### ISSUE TITLE
File `pdftexcmds.sty' not found.

### ISSUE THREAD

**Issue by r0b0** [rstropek/pandoc-latex#1]
Hi,

The latest build of your amazing docker image fails with the following message:

```
Error producing PDF.
! LaTeX Error: File `pdftexcmds.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.107 \RequirePackage{pdftexcmds}[2009/04/10]
```

**Comment by rstropek** [comment]
Thank you for pointing that out. Added missing package to Dockerfile. Docker image build should be done in a few minutes.

Greetings,
Rainer.
