### ISSUE TITLE
Create a Docker tag different than latest

### ISSUE THREAD

**Issue by vincent-zurczak** [rstropek/pandoc-latex#3]
Hi,

Could you create a Docker tag for the latest image?  
Using the same version than the base image would be great, i.e. `rstropek/pandoc-latex:2.9.1.1`.

**Comment by rstropek** [comment]
We could create tags according to version numbers of base image in GitHub to trigger Docker Hub builds that use them as the tag of the repository in Docker Hub. Ok for you?

**Comment by vincent-zurczak** [comment]
Indeed, tags should be the same than the base image.  
And yes, we could have automatic builds when we create a git tag. If you want, I can upgrade the Travis-CI file to this automatically.

**Comment by rstropek** [comment]
No need for Travis-CI in this case. I have already set up automatic build with Docker Hub.

**Comment by vincent-zurczak** [comment]
OK. :+1:   
Shouldn't we run tests work before tagging the master branch?
