### ISSUE TITLE
Working directory

### ISSUE THREAD

**Issue by andr1976** [rstropek/pandoc-latex#5]
@rstropek, thanks a lot, it solved a lot of headache with latex packages not being installed. 
I have managed to create a workflow running pandoc and uploading a created pdf as an artefact. However I can only make this work if I have the markdown source file in the "root" dir of my repo. Ultimately I would like to have the source in docs/ (along with images docs/img/ reference docs/reference.bib etc). what should I change in my args?

args: --toc --filter pandoc-crossref --citeproc --bibliography=docs/references.bib --top-level-division=chapter  --number-sections --listings  --template docs/eisvogel.tex --output=output/Test.pdf  Manual.md

**Comment by rstropek** [comment]
I tested putting the source in *docs/* and had no problems with it. Here is the command I used: `docker run --rm -v `pwd`:/data rstropek/pandoc-latex -f markdown --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex -t latex -o mydoc.pdf --metadata-file docs/mydoc.yaml docs/mydoc.md`

**Comment by rstropek** [comment]
Will close this issue. Feel free to create a new one or comment in case of follow-up questions.
