### ISSUE TITLE
Missing packages background and everypage

### ISSUE THREAD

**Issue by cyberaguiar** [rstropek/pandoc-latex#7]
I got this error when using page-background.

cat doc.md 
---
title: "Title"
subtitle: "Subtitle"
titlepage: true,
titlepage-text-color: "000000"
titlepage-rule-color: "360049"
titlepage-rule-height: 0
titlepage-background: "./background1.pdf"
page-background: "./background2.pdf"
geometry: "a4paper,left=2cm,bottom=3cm,top=2cm,right=2cm"
linkcolor: blue
...

Some text

docker run --rm -v "`pwd`":/data -w /data rstropek/pandoc-latex:latest -f markdown --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex -t latex -o report.pdf doc.md --highlight-style tango
Error producing PDF.
! LaTeX Error: File `background.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.154 ^^M

**Comment by rstropek** [comment]
Solved by #8, correct?

**Comment by cyberaguiar** [comment]
Yes, after the changes the pdf is generated without errors.
